spring:
    datasource:
        url: jdbc:mysql://localhost:3306/grad-dev?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: rladudfo1
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create
        show-sql: true
    messages:
        basename: i18n/exception
        encoding: UTF-8
    url:
        base: localhost
    social:
        kakao:
            client_id: 123
            redirect: redirect_tmp_url
